# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 302e2aae3d039fe865cdb74017eb414443806183b89382de0d1ebb3ade3c6cc0d1453e1408a737b747ad31094b5a91010708401581318ed04b3380dcedd00419

test:
  secret_key_base: 2ebb5b03b7efb9eed2e90f2ecd7566fef91cd510ebfae5f8d33c63b61b909147a1410470f03969e46bfec7612bde49a1c73aac07b7d6e0476c1f607df0715e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
